name: mybinder-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab
  - jupyter-server-proxy
  - nodejs  # Installing Node.js through Conda which includes npm
  - pip:
      - git+https://github.com/username/repository.git  # If any additional Python packages need to be installed
